name: deliverzler
description: Deliverzler
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  app_tracking_transparency: ^2.0.2+2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.14
  cloud_functions: ^3.2.14
  collection: null
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  dropdown_button2: ^1.5.2
  equatable: ^2.0.3
  firebase_auth: ^3.3.18
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  firebase_storage: ^10.2.5
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_fadein: ^2.0.0
  flutter_gen_runner: ^4.1.6
  flutter_hooks: ^0.18.2+1
  flutter_keyboard_visibility: ^5.2.0
  flutter_local_notifications: ^9.3.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.5
  flutter_platform_widgets: ^1.20.0
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.0.3
  geolocator: ^8.2.0
  geolocator_android: ^3.1.8
  get: ^4.6.1
  google_maps_flutter: ^2.1.1
  hooks_riverpod: ^2.0.0-dev.4
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  intl_phone_number_input: ^0.7.0+2
  keyboard_attachable: ^2.1.0
  keyboard_visibility: ^0.5.6
  location: ^4.3.0
  lottie: ^1.2.1
  material_floating_search_bar: ^0.3.6
  path_provider: ^2.0.10
  phone_number: ^0.12.0+2
  pin_code_fields: ^7.4.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.9
  sqflite: ^2.0.1
  timeago: ^3.2.2
  url_launcher: ^6.0.20
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3

flutter_icons:
  image_path_android: "assets/images/core/icon.png"
  image_path_ios: "assets/images/core/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#121B24"
  adaptive_icon_foreground: "assets/images/core/icon_adaptive_fore.png"

flutter_native_splash:
  color: "#FAFAFA"
  color_dark: "#303030"
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  android_12:
    image: "assets/images/welcome/transparent_splash_icon.png"
    image_dark: "assets/images/welcome/transparent_splash_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/json/
    - assets/json/map_styles/
    - assets/images/welcome/
    - assets/images/login/
    - assets/images/core/
    - assets/images/core/backgrounds/
    - assets/images/core/dialog_widget_icons/
    - assets/images/app_icons/
    - assets/images/app_icons/screens_icons/
    - assets/images/app_icons/languages_icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 900
    - family: tajawal
      fonts:
        - asset: assets/fonts/tajawal.ttf
        - asset: assets/fonts/tajawal_bold.ttf
          weight: 900
